# Generated by Django 5.2.13 on 2026-04-23 04:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('trainee', 'Trainee'), ('software_engineer', 'Software Engineer'), ('senior_software_engineer', 'Senior Software Engineer'), ('team_lead', 'Team Lead'), ('manager', 'Manager'), ('engineering_manager', 'Engineering Manager'), ('cto', 'CTO'), ('hr', 'HR')], default='trainee', max_length=50),
        ),
    ]
